### ISSUE TITLE
Modifying theme

### ISSUE THREAD

**Issue by Scorpovi4** [EryouHao/brackets-dark-pro#1]
Lovely theme in VS and in Brackets, almost single theme with very useful color palette, but in JSON files a props and values are the same and yeah, that's like in original Brackets theme but it spoil visual perception and it's better to separete with color.

**Comment by EryouHao** [comment]
@Scorpovi4 , I just released a new version and have optimized the color of the json file.

thanks!

I like light theme, so I use Brackets Light Pro usually.
